### ISSUE TITLE
fix test and move test sessions to `nox`

### ISSUE THREAD

**Issue by 12rambau** [eralchemy/eralchemy#107]
I realized the test were not robust enough to continue working on my set-up, some issues related to the isolation of environments. 
I'm not a big fan of the tox syntax and I prefer to stick to the pure python `nox` sessions that essentially do the same thing. 

We need to:
- [ ] create some default session (lint, mypy etc..)  
- [ ] create a test session 
- [ ] make sure the test session run succesfully locally

**Comment by maurerle** [comment]
I think this is closed and released. If there is anything else to do, just mention it and reopen :)
