### ISSUE TITLE
10.07.2024 - Public Online Meetup for further development and communication

### ISSUE THREAD

**Issue by maurerle** [eralchemy/eralchemy#119]
Hi,
I would like to have a short meetup of half an hour or something to discuss further steps and get to know each other a little bit.
What do you think about doing this in the upcoming weeks?
- @Alexis-benoist (original eralchemy creator)
- @12rambau (current eralchemy owner)
- @kasium @paoliniluis (eralchemy2 contributors)
- @bollwyvl (maintains [eralchemy2-feedstock](https://github.com/conda-forge/eralchemy2-feedstock)
- everyone else who likes to join.

We can meet online on Jitsi at: https://meet.freifunk-aachen.de/eralchemy without any login.

What do you think about this idea?

**Comment by 12rambau** [comment]
Very nice idea indeed ! I'm on CET time zone as well as @maurerle  and @Alexis-benoist  but I don't know about the others. 
If we want to schedule something that would make it easier.

I will be in holydays starting on the 13th with 0 access to the web (the only I found to unplug myself from my computer) so if it needs to happen for me it needs to be next week.

**Comment by maurerle** [comment]
I would have 10th of July, 19:00 CET in mind, if this works for everyone :)
If this does not work out for anyone, just propose a different time/date.

If this gets to complicated, we can also create a doodle and do it in a few weeks..

**Comment by 12rambau** [comment]
let's go doodle or rallly. Can you set it up from your side ?

**Comment by maurerle** [comment]
Sure, I am using the privacy-focused open-source Nuudel:
https://nuudel.digitalcourage.de/EzdOP9fZJexd1zFU

**Comment by kasium** [comment]
Thanks a lot for setting this up! Highly appreciated that you want to spend the time to drive the topic and the community forward!

**Comment by paoliniluis** [comment]
👍🏻 from my end, I'm in Argentina but can adapt to EU timezones without any issues

**Comment by maurerle** [comment]
@paoliniluis @kasium could you add your availability to https://nuudel.digitalcourage.de/EzdOP9fZJexd1zFU please? :blush:

**Comment by kasium** [comment]
@maurerle done 😄

**Comment by maurerle** [comment]
So the meeting will take place at 09.07.2024 at 18:00 CET at https://meet.freifunk-aachen.de/eralchemy

Feel free to join!

**Comment by paoliniluis** [comment]
Thanks for the invite, I'll be giving a webinar at that time so if you can please record the meeting and leave it here I will greatly appreciate it

**Comment by kasium** [comment]
I'm also unable to join today. A recording or a short summary would be great. Thanks!

**Comment by maurerle** [comment]
Sorry - it will be Wednesday the 10.07.2024 at 18:00 CET - otherwise I would be alone according to the doodle.
Sorry for confusion.
I will provide a short summary afterwards :blush:

**Comment by maurerle** [comment]
# eralchemy meeting

Attendees:

- @12rambau
- @kasium
- @maurerle

## Short introduction round

## Technical discussions

### future packaging of eralchemy2

* eralchemy2 will become a wrapper package without breaking compatibility
* which only includes eralchemy and exposes it as eralchemy2
* just like https://pypi.org/project/distribute/ was done for setuptools
* eralchemy becomes the main package

### workflow

- we will always try to use merge commits
- we will try to await feedback from other maintainers on PRs
- @maurerle and @12rambau will be owner of the org and pypi
	- @kasium will be granted maintainer rights
- next release will be 1.5.0
- NEWS.rst will be removed - in favor of github release notes for the future

### tooling

- we will use nox and github actions
- we will use a release workflow similar to [this](https://github.com/SAP/sqlalchemy-hana/blob/main/.github/workflows/release.yml)
- there will be docs released on eralchemy.readthedocs.io
- we will be [REUSE](https://reuse.software/) compliant
- we will use ruff for linting and formatting in a way that is compatible with black and isort

### next steps

- tests/CI should pass (@12rambau)
- drawing of exact relations will be investigated by @maurerle (#72)
- @kasium will check which dependencies are required on windows (#47, #90)

We will work asynchronously and see if other meetings like this are needed :)
