### ISSUE TITLE
How to handle override naming schemes?

### ISSUE THREAD

**Issue by talaniz** [eralchemy/eralchemy#27]
I'm getting the following exception when I run the example postgresql string on my database--

```
sqlalchemy.exc.ArgumentError: WARNING: when configuring property 'mttakertradetype' on Mapper|RequestNew|RequestNew, column 'mttakertradetype' conflicts with property '<RelationshipProperty at 0x39472b8; mttakertradetype>'. To resolve this, map the column to the class under a different name in the 'properties' dictionary.  Or, to remove all awareness of the
column entirely (including its availability as a foreign key), use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically which table columns get mapped.
As defined here http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/automap.html#overriding-naming-schemes
```
My string - `eralchemy -i 'postgresql+psycopg2://postgres:just4fun!@@10.10.100.85:5432/bridge_latest' -o filtered.er -x temp audit`

This error comes from sqlalchemy, referenced in this [ticket](https://bitbucket.org/zzzeek/sqlalchemy/issues/3449/automap_base-fails-on-my-database) which suggests using an [overriding naming scheme strategy](http://docs.sqlalchemy.org/en/rel_1_0/orm/extensions/automap.html#overriding-naming-schemes). Does eralchemy provide any way to do this?

**Comment by maurerle** [comment]
This should be fixed in 40c9b9c8199e9740695931d48a6f90f9846fd5d8 - see #31 
If this still occurs, please give notice.
