### ISSUE TITLE
For all users trying to install ERAlchemy on Windows 10

### ISSUE THREAD

**Issue by klondikemarlen** [eralchemy/eralchemy#47]
After much effort I gave up and installed:

> Bash on Ubuntu on Windows

1. Open PowerShell as Administrator and run:
PS:> `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
2. Restart your computer when prompted.
3. Install [Ubuntu](https://www.microsoft.com/store/p/ubuntu/9nblggh4msv6):

More info @ https://docs.microsoft.com/en-us/windows/wsl/install-win10.

Next open up your new bash terminal (Start > bash).
Then run your basic update all command. 
1. $`sudo apt-get update`  https://askubuntu.com/a/196777/793432.
2. $`sudo apt-get install python-2.7 python-pip`
3. $`sudo pip install graphviz`
4. $`sudo pip install eralchemy`
5. $`sudo pip install SQLAlchemy`

You will also need to install the python driver for your database.
eg: `sudo pip install mysql-python` for MySQL driver. See http://docs.sqlalchemy.org/en/latest/dialects/mysql.html#dialect-mysql
And you will need to install MySQL (if you are using that).
eg: `sudo apt-get install mysql-server`
See https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

And you will probably need to set up the MySQL database just like you would for Windows.

If you are missing any modules I recommend googling for them like so:

> apt-get install some-missing-module ubuntu

Compatability: **Windows Subsystem for Linux is only available on x64 editions of Windows 10 and can be activated on Windows 10 version 1607 and later.**

**Comment by peterdavidsonONE** [comment]
This worked for me on a fresh ubuntu 18.04 WSL:

sudo apt-get update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python2.7
sudo apt-get install python-pip
sudo apt-get install libgraphviz-dev
sudo pip install graphviz
sudo pip install eralchemy
sudo pip install SQLAlchemy
sudo apt-get install postgresql-11
sudo apt-get install python-psycopg2

**Comment by choj** [comment]
I was able to install it on win10 via:

 conda install -c alubbock pygraphviz
 pip install eralchemy 
 pip install graphviz

Then installing the graphviz binaries: https://www.graphviz.org/download/ and adding them to the Windows PATH.

Then editing eralchemy main.py to remove the pygraphviz dependecy, and change it to use graphviz:
 # from pygraphviz.agraph import AGraph
from graphviz import Source, render, Digraph
...
    # graph = AGraph()
    # graph = graph.from_string(dot_file)
    # graph.draw(path=output, prog='dot', format=extension)
    
    # new code added by james cho
    graph = Digraph(name="graph", engine='dot')
    graph.src = Source(dot_file, filename=None, directory=None, format=extension, engine='dot', encoding='utf-8')
    graph.src.render('dot', extension, output, renderer='cairo', formatter='cairo')

**Comment by kasium** [comment]
I understand the frustation installing pygraphviz but this is not the fault of eralchemy. As explained in #90, you can install the latest versions of all libraries when following the pygraphviz documentation. However, I created #121 to explorer alternatives to pygraphviz.

@maurerle you can close the issue if you want
