### ISSUE TITLE
Proposition: allow multiple output formats

### ISSUE THREAD

**Issue by bmedici** [eralchemy/eralchemy#57]
Hello,

For now, we can specify one `-o filename.format` parameter.
It would be useful to be able to passe multiple `-o` parameters, or a filename base and a list of extensions/formats, on a single run.
I find myself running multiple commands to generate SVG, PNG and PDF formats for each .er file.

Have a good day !

**Comment by maurerle** [comment]
I would rather keep this as is for simplicity.
Running the cli multiple times is fine - alternatively you can write a python script which calls `eralchemy` multiple times, or create a shell script for this.

**Comment by maurerle** [comment]
I also do not see an easy way how this would work with the current -m param for output mode (which would have to be provided multiple times as well). So this is not planned for now.

**Comment by bmedici** [comment]
4.5 years to get a response seems a reasonable thing :)
Have a good day
