### ISSUE TITLE
When i pass a schema to the declaritive_base it breaks the whole drawing

### ISSUE THREAD

**Issue by valeriozhang** [eralchemy/eralchemy#61]
```
metadata = MetaData(schema="test_db")
Base = declarative_base(metadata=metadata)
```

When i add in a custom schema all the relationships break? Any ideeas?

**Comment by maurerle** [comment]
Generally, it is supported to specify only custom schemas:
`$ eralchemy -i 'postgresql+psycopg2://username:password@hostname:5432/databasename' -s "schema1, schema2"`
also see #59 

Does this fix your issue?
