### ISSUE TITLE
fix versionining, please release 1.5+

### ISSUE THREAD

**Issue by praiskup** [eralchemy/eralchemy#66]
Cheers!  Today I created release monitoring entry [1] and I noticed that the latest released version of eralchemy is v1.4.0, but according to github page - the latest seems to be 1.2.10.
To not confuse anyone, it would be nice to not continue with 1.2 serie, but bump the version right to 1.5.0+

[1] https://release-monitoring.org/project/21897/

**Comment by praiskup** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1754207

**Comment by maurerle** [comment]
as of #119 the next release of eralchemy will be v1.5.0 - which will be a higher version than eralchemy2 (v1.4.1) and eralchemy (1.2.10).
So I will close this issue.
