### ISSUE TITLE
Entities do not align

### ISSUE THREAD

**Issue by benbogart** [eralchemy/eralchemy#83]
I am using eralchemy on a MySQL database.

The relationship indicator lines in the produced graph do not align with the columns in the erd.

The tables are defined like this:
CREATE TABLE `cpsc_enrollment_info` (
  `ContractNumber` varchar(256) NOT NULL,
  `PlanID` varchar(256) NOT NULL,
  `SSACode` int(11) NOT NULL,
  `FIPSCode` int(11) DEFAULT NULL,
  `State` varchar(2) DEFAULT NULL,
  `County` varchar(256) DEFAULT NULL,
  `Enrollment` int(11) DEFAULT NULL,
  `Period` date NOT NULL,
  PRIMARY KEY (`ContractNumber`,`PlanID`,`SSACode`,`Period`),
  CONSTRAINT `cpsc_enrollment_info_ibfk_1` FOREIGN KEY (`ContractNumber`, `PlanID`) REFERENCES `cpsc_contract_info` (`ContractNumber`, `PlanID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cpsc_contract_info` (
  `ContractNumber` varchar(256) NOT NULL,
  `PlanID` varchar(256) NOT NULL,
  `OrganizationType` varchar(256) DEFAULT NULL,
  `PlanType` varchar(256) DEFAULT NULL,
  `OffersPartD` tinyint(1) DEFAULT NULL,
  `SNPPlan` tinyint(1) DEFAULT NULL,
  `EGHP` tinyint(1) DEFAULT NULL,
  `OrganizationName` varchar(256) DEFAULT NULL,
  `OrganizationMarketingName` varchar(256) DEFAULT NULL,
  `PlanName` varchar(256) DEFAULT NULL,
  `ParentOrganization` varchar(256) DEFAULT NULL,
  `ContractEffectiveDate` date DEFAULT NULL,
  `Period` date DEFAULT NULL,
  PRIMARY KEY (`ContractNumber`,`PlanID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

The erd produced looks like this.  ContracNumber, PlanID should be connected to ContractNumber, PlanID in each table.
![Screen Shot 2021-06-30 at 11 26 02 AM](https://user-images.githubusercontent.com/29614010/123991320-9dc32380-d998-11eb-8307-7ae8bbf92efa.png)

This indicates that there is a connection between the tables but doesn't show which columns.  Is this a bug?  If it is expected behavior what can I pursue to fix it?

**Comment by davidjb99** [comment]
I’m not sure if the author still maintains this package but there is a PR addressing this  https://github.com/Alexis-benoist/eralchemy/pull/72

@Alexis-benoist do you intend to merger any new PRs?

**Comment by maurerle** [comment]
fixed in #72
