### ISSUE TITLE
Upgrading SQLAlchemy can break ERAlchemy

### ISSUE THREAD

**Issue by qb14cj** [eralchemy/eralchemy#91]
As of this date, the latest release of SQLAlchemy is **1.4.37**. This release of SQLAlchemy causes the `render_er` function to throw an exception. I'm guessing a number of releases earlier than this one will probably have the same effect. The latest release of SQLAlchemy that successfully creates the ER diagram that I have used is **1.3.24**.

My recommendation: `pip install SQLAlchemy==1.3.24` Either this or this library has to be updated which I may have to do anyway for the sake of our customized version of JupyterLab. Don't know yet if downgrading SQLAlchemy will cause a problem for another Python library, but I am sure my users will let me know soon enough.

**Comment by maurerle** [comment]
This is is fixed in: 02d84429f6757c34ace83a723e5c3495c2309031
from https://github.com/sturzaam/eralchemy/pull/1
also see #80
