### ISSUE TITLE
Getting CI back on track

### ISSUE THREAD

**Issue by florimondmanca** [eralchemy/eralchemy#92]
Hi there,

I was looking at using this tool as a handy "plugged onto SQLAlchemy" replacement to a custom script. I hit #80 and saw that #86 might fix it. Unfortunately there are unrelated CI errors which seem to have stalled development.

I'm opening this issue because I think the first step towards getting this project in shape so we can fix items such as #80 would be having CI pass on `master` again. Right now this project has over 100 forks which sometimes exist just so people and make the necessary fixes. 

I am going to investigate and report, or open a PR if I find what needs fixing. :)

**Comment by maurerle** [comment]
The CI currently builds fine :)
