### ISSUE TITLE
[eralchemy2] Fork of ERAlchemy for further development

### ISSUE THREAD

**Issue by maurerle** [eralchemy/eralchemy#94]
Unfortunatley, this repo became stale for a quite a while.

As it is not compatible with current SQLAlchemy versions I created a fork of it.
I wrote Alexis by mail and asked if he could integrate the needed change, but did not get an answer for a few months.

My fork can be found here:
https://github.com/maurerle/eralchemy2/

Or installed from here:
https://pypi.org/project/eralchemy2/

Or by writing
`pip install eralchemy2`

You can support further development there.
If Alexis comes back to this repo I would be happily handing this back over to the original eralchemy which was very good supported for years.
Thank you @Alexis-benoist - I hope this is also okay for you.

**Comment by kasium** [comment]
@maurerle thanks a lot for your efforts and the fork

**Comment by potiuk** [comment]
Relly cool that you've done the fork and released it @maurerle ! Thanks a lot - we just merged a PR in Apache Airlfow that helps us to produce automatically (via pre-commit) generated documentation for our internal DB schema thanks to your fork https://github.com/apache/airflow/pull/26217).

:bow:

**Comment by evilaliv3** [comment]
Thank you @maurerle for your effort maintaining eralchemy !

We have just updated using eralchemy2 also for @globaleaks: https://github.com/globaleaks/GlobaLeaks/blob/devel/documentation/data/database.pdf

**Comment by kasium** [comment]
@maurerle can you please comment on the current state and maybe just close this one?

**Comment by maurerle** [comment]
The latest release is now available on eralchemy:
https://pypi.org/project/eralchemy/

You can read more about it here:
https://github.com/eralchemy/eralchemy/releases/tag/v1.5.0

and install it using `pip install eralchemy[graphviz]`.
