### ISSUE TITLE
in newer version of sqlalchemy table.c._data is gone

### ISSUE THREAD

**Issue by gbrault** [eralchemy/eralchemy#96]
[see](https://github.com/Alexis-benoist/eralchemy/blob/4f9dbdabd032bc293c1ab68174402af5954720d6/eralchemy/sqla.py#L50)

should replace table.c._data with table.columns

**Comment by xperrylinn** [comment]
@gbrault, thank you for sharing this!

**Comment by maurerle** [comment]
This is is fixed in: 02d84429f6757c34ace83a723e5c3495c2309031
from https://github.com/sturzaam/eralchemy/pull/1
also see #80
